name: bike_mso
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  geolocator: ^5.1.1+1
  flutter_spinkit: ^3.1.0
  google_maps_flutter: ^0.5.20+3
  flutter_polyline_points: ^0.1.0
  http: ^0.12.0+2
  firebase_core: ^0.4.0+8
  firebase_auth: ^0.14.0+2
  cloud_firestore: ^0.12.9
  expandable: ^3.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Lora
      fonts:
        - asset: fonts/Lora-Regular.ttf
        - asset: fonts/Lora-RegularItalic.ttf
        - asset: fonts/Lora-Bold.ttf
        - asset: fonts/Lora-BoldItalic.ttf
          style: italic

    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather-Regular.ttf
        - asset: fonts/Merriweather-RegularItalic.ttf
        - asset: fonts/Merriweather-Bold.ttf
        - asset: fonts/Merriweather-BoldItalic.ttf
          style: italic
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-RegularItalic.ttf
        - asset: fonts/RobotoMono-Bold.ttf
        - asset: fonts/RobotoMono-BoldItalic.ttf
          style: italic


