// When moving these to database you must remove everyother '\' because firestore does not parse escape chars the same

const String kDeerCreekSneakPoly =
    "yw~|Gx`vvTgHA?OiGAMa@DYAASZQIOa@g@m@MYS}@Ey@?a@JqA`@uA?[aABaFC_@NwD??KsD?Ec@gMCSMbCmKt@}@Tc@Ts@dIsYxK_`@b@_Ft@qAC}E~@uIo@iR}@oTC_[}AqRyBwSy@aPJkCm@{Hk@mCwAqFwAaD_DkGeGwQsAgDcAeBuJoOm@QsAWq@gAu@cDeJsWoAcEe@sDcAwFQiDIiDGqGMaZOcSm@sl@Ew@tE{GVs@T{FHwHXiDnAaUXgAhCaFdByAxXuPHHPHN|@LPHFP@^GTStA_BbAsAvBmCZc@`@[\\Gp@D`Cq@ZCp@OXEf@?VDXAxBHfARNHtAFn@Pv@Fd@Hf@?\\Gb@?^Ip@EbAAt@I~@ENDZGp@?\\HRNbAlBRVL@PAh@Qj@AT@THv@Nx@d@NXHl@CzBK`BApBR`A|@zBPNd@Hb@M\\FfAF|@GdAF|@`@n@d@PRDTETML[Cg@Qc@Bi@LWVc@n@sAdA]`@[Pi@JWBg@PqABYA]Ko@y@O[a@e@e@a@q@YMOQIOSG?EDIPAJFPn@`@Zt@Pj@^~@b@lBj@vARr@TPl@HVNb@\\v@~@N`@LJTh@J`@Fr@@^EdBDJB|@Db@Ll@LDPCF]PYh@c@LA`@Hf@TVT`AhBTHJEFIPk@`@Qb@c@d@Qn@[N?|@Y~@Qd@Gn@?z@XHFX`@Hb@D|AKbCFVFDLJH@DGR?f@N`Ad@r@b@p@J\\A^@JCN?z@ZXRb@r@Fv@WlDMv@i@`B?PDXLHh@KvABVC\\HVPR^Np@Bb@?fA@RFTTPFLXBh@Jv@t@t@j@`@j@b@dAvAdC\\fA^lBVdCDn@?j@UhCKd@OrBAZBXDFF?NOVeAJSFERAx@c@Vi@NMPIPg@Po@Xi@LIX?PPJXBdANbBRl@XNj@H~BPr@Zh@`@d@l@HVD~@IrAHf@RDd@ARFf@Zt@Zd@h@Jd@Ah@IpAa@xDDd@NVTHx@JdBAjBa@dAYhA_@tBW\\SZMPAj@?VF^HPH`@r@h@jBXtANrAN|C?d@KdCAbBCh@OzA[PFfA?fA[lC?\\ZlAZXdCMfAV`Ah@K\\Kr@Et@EXEhAKj@AnA]zFM~CQbBM~CC|BKdAMvE]|FIrBGVe@rKMjEAbBM|BIx@ShF]fE?rDM~CQhBcA`AYN}ARSNQZ?b@l@zBHdAu@`F[pDgA|Ds@r@OFS?w@_@a@][[m@Om@Q_@@_@I_@SEW{@uA[MMDIHo@vAKd@K|@EPUf@?FRDNZNnATpAXr@HFXd@RPHNVv@Hr@?PKt@_@jBGj@O|@EJILGRBFLPDPBh@J]?SBID?BHHb@@pANlCA|@Mn@KFw@PSV?HEFFDJZHBBHDB?ZHZ`@D|@ERAFFr@JT^b@\\l@n@x@j@ZLf@Zf@V?JT\\BLDBFB@n@Jr@HRTNNZDN@THN@Nz@jBZlAFEp@b@P?p@HEH?Lp@v@FZ\\jAPPZBHV^RRr@pArBHXBTE`CaAdGc@|BC`@o@pAaBbBG`@JZpBd@r@p@PfAk@pFEfAPbEQfAQv@u@lAs@PSd@HdEQlA_A|BQt@g@ZIZBbCj@`D`@nABl@Qh@sAt@cA|@Jb@v@Zf@j@fHdLf@|@VjBZxME@Kh@o@fA[Rk@z@i@b@g@f@ULSZsAXmAb@QPc@F}@Z}Bn@iAh@Q?y@ZcC`@CJBLv@d@h@j@CFq@Zc@GQIK@EN@Fb@b@VPd@JZCnAP`AFFG^HP?JFAHg@XW?EH@FjB~@h@`@r@P@PEHu@RHNTFj@@ANGPyBpAMNk@PSPeAZ?PaAl@_APYN_L?yTGoC?_GNe@JqANoBAmE@MQoA?bDPeA?MQoJ@cJ?wIAiQ?";

const String kLoloRide =
    "gt`}GxgxvTe@??oBS?GHEnAOtAa@jAW`@[SW~@m@~@]Vc@P_@l@mCpDSZuAnAMVo@lBYZ@j@q@|BQpA[fFGZe@r@IX@bGBnANrA@`BLTVJv@FlAhArAdA`Aj@|@t@\\Rh@DnApA`@j@rE|DLX\\RhBfBj@ZvBlBd@z@ARBFh@?|@dApAfAbB`Bd@R`Q~ObEzDf@j@\\Tb@t@LL\\HZj@l@`@t@v@`BzAf@^^b@pCfCRLlIfIZNfG~F~CpC^b@CETFHFb@v@\\\\VL\\XpAvAl@b@t@n@bAbAFJdAfAfAx@lAjAn@`@xAfBf@\\x@z@f@\\PVLXlDbDl@t@pC~BtHbHj@Nb@v@lIxHlDjD`EpD~C~C`@j@PHb@b@Zj@zEdQxCxJvJz\\~@rD`DrIt@|@`BxAv@?d@QGnAh@l@Lr@b@bBLt@Z`@lBjInWvnAbHb\\rGdXb@zArAtCpAzBlA`BjAjAf@i@tIpLfIpKtBrDdBfFlAbGv@hDxBbGfEhI~FnL|GdMdCzDL[zC|DbEvEjBvA~QdJlBPxAQzCi@bBo@nCwAnBu@vB_AxDs@pB?tCX|Cn@bCz@`r@x[tA\\vBL|BQnAs@`DgC~BeCd_@od@xg@}m@vPeSnB{DhCmGnCoFtCaDjCwAdC[|CIdCZdQhDOpAu@hFObC?nAkA?jA??oANcCt@iFNqAeQiDeC[}CHeCZkCvAuC`DoCnFiClGoBzDwPdSyg@|m@e_@nd@_CdCaDfCoAr@}BPwBMuA]ar@y[cC{@}Co@uCYqB?yDr@wB~@oBt@oCvAcBn@{Ch@yAPmBQ_ReJkBwAcEwE{C}DeCcE{@eAgAwBiRs_@qBuG}@sDq@qD}AgF{AkDkUuZWh@g@h@kAkAmAaBqA{BsAuCc@{AsGeXcHc\\oWwnAmBkI[a@Mu@c@cBMs@i@m@FoAe@Pw@?aByAu@}@aDsI_AsDwJ{\\yCyJ{EeQ[k@c@c@QIa@k@CoFBuPCtPBnF_D_DaEqDmDkDmIyHc@w@k@OuHcHqC_Cm@u@oDcDEWW[IAUWo@a@_@g@i@_@KK@GCQaBuAQUg@k@GAyAwA[_@Q]s@}@k@c@[IMQG?_Ak@]]s@eASOWGOIm@aAOMS??F_@c@_DqCgG_G[OmIgISMqCgC_@c@g@_@aB{Au@w@m@a@[k@]IMMc@u@]Ug@k@mRmQwCmCe@ScBaBqAgA}@eAYB?s@]@Yi@wBmBk@[iBgB]SMYsE}Da@k@oAqAi@E]S}@u@aAk@sAeAmAiAw@GWKMUAaBOsACoAAcGHYd@s@F[ZgFPqAp@}BAk@X[n@mBFDBVB@";

const String kKimWilliams =
    "y{`}GptwvTjBcEV{A@wACG}@c@\\oCcBu@Cc@?}@h@}@L_ALWv@mDQoIKsAhE`@CgGBuAAmFFi@XiAT_BbCmKt@}@Tc@Ts@dIsYxK_`@`@kE?B_@YAq@B[AULy@A[De@Ak@MECKFeA@w@AGYYWgDEaBD[A_APcCKgETgAG{BR{DZgAMm@P{EIcGi@eGToAMgCUgB?w@KoADa@CiAF_AFW}A{HyAmEi@yF`@sGF[]YD@FJBLr@ItBbS|ApRB~Z|@nTn@hR_AtIB|Eu@pAc@~EyK~_@eIrYUr@Ub@u@|@cClKU~AYhAGh@@lFCtADzIEhBP|F@bLt@`BPHPN@tw@kK?eEEeB?YQ[YCWGEYv@OPOEk@e@c@GMQQ_ASWUCfBa@RQh@yALIN?PJd@dA\\FLRb@AlCqD^m@bE_RjBcGd@_DHw@";

const String breweryRide =
    "ioa}GjaxvTz@yA^i@d@eAhAqDbCnAxDzBtInEp@P`@DjA??fH~D@BnH?de@BnHKvZ@dAXC|@dApAfAbB`Bd@RdWzUf@j@\\Tb@t@LL\\HZj@l@`@t@v@`BzAf@^^b@pCfCRLlIfIZNfG~F~CpC^b@CEF?NFRPf@r@ZX\\T`AhAlA~@`@Pf@^vAtAb@r@L@TN`Av@l@v@~@z@DPd@`@f@l@^XPR~@z@PRFJ?CB|@JO?OnDfDl@t@pC~BtHbHj@Nb@v@lIxHlDjD`EpD~C~CCoFB_OC~NBnF_D_DaEqDmDkDmIyHi@a@e@e@uHcHqC_Cm@u@oDgD?NKNCy@MEgCyBOQGQIGoAoAe@[}@aAaAy@y@gAq@k@SUg@g@IEOHEOKOKA_@e@SOGOSSISi@g@IAu@m@a@w@MMCFMG?F_@c@_DqCgG_G[OmIgISMqCgC_@c@g@_@aB{Au@w@m@a@[k@]IMMc@u@]Ug@k@cE{DaQ_Pe@ScBaBqAgA}@eAi@?CG@Se@{@wBmBk@[iBgB]SMYsE}Da@k@oAqAi@E]S}@u@aAk@sAeAmAiAw@GWKITF|@BxDCpEDpBKvCDzB?bBDXE\\IVInCBnHSzBBl@C`BBfAA|BBhBKR?L@d@R?BHArIBFZPBH@rBDFbB?@ZAbEsP?@mMAlMrP?@cEA[cB?EGAsBCI[QCG@sICIS?Ae@?MJSCiB@}BCgABaBCm@R{BAiGaUEiCBFuBCMmFBGUMSGSAOJ_A?i@TaABeCCgB_@KCG]GOBGoAD_BCqAGEKKjAsGl@kCgIsEc@_@C}@RaBYw@GoA?ce@LkAlBwJh@cBtBsFbCwFrBiFJQZAZPl@RtC~ArAcH~DbC`Bz@nFvC";
